name: CI Pipeline

on:
  push:
    branches:
      - '*'

permissions:
  checks: write
  contents: read

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.25.5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build engine
        run: make engine

      - name: Build webserver
        run: make webserver

      - name: Test
        run: make test

          #      - name: Upload binaries
          #        uses: actions/upload-artifact@v4
          #        with:
          #          name: app-binaries
          #          path: bin/
          #
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

          #      - name: Download binaries
          #        uses: actions/download-artifact@v4
          #        with:
          #          name: app-binaries
          #          path: bin/
          #
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: |
          docker build -f deploy/engine.Dockerfile -t engine:ci .
          docker build -f deploy/webserver.Dockerfile -t webserver:ci .

      - name: Deploy containers on runner
        run: |
          sudo apt install docker-compose
          sudo mkdir /tmp/deployment_home
          sudo cp config-docker.json /tmp/deployment_home/config.json
          sudo cp engine.json /tmp/deployment_home/
          docker-compose --env-file deploy/.env.ci -f deploy/app-compose.yaml up -d

      - name: Smoke test
        run: |
          sleep 5
          curl -f http://localhost:8080/health
